[build]
  command = "npm run build"  # oder der Befehl, um den SvelteKit-Build durchzuführen
  publish = "site/server/build"  # Verzeichnis, in dem der SvelteKit-Build liegt
  base = "site/server"  # Basisverzeichnis für den Build-Prozess