version: 2
updates:
  - package-ecosystem: "npm"
    directory: "site/en/server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "site/en/offline/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "site/de/server/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "site/de/offline/"
    schedule:
      interval: "daily"
