[build]
  command = "npm run build"  # oder der Befehl, um den SvelteKit-Build durchzuführen
  publish = "site/offline/build"  # Verzeichnis, in dem der SvelteKit-Build liegt
  base = "site/offline"  # Basisverzeichnis für den Build-Prozess